# Generated by Django 5.1.2 on 2024-10-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PowerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricnumber', models.CharField(max_length=11)),
                ('account', models.CharField(max_length=10)),
                ('registered', models.BooleanField(default=False)),
                ('regdate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceuuid', models.CharField(max_length=36)),
                ('name', models.CharField(choices=[('name1', 'Name 1'), ('name2', 'Name 2')], max_length=10)),
                ('value', models.FloatField()),
                ('datatime', models.BigIntegerField()),
                ('createtime', models.BigIntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['deviceuuid', 'name'], name='api_deviced_deviceu_0d9589_idx'), models.Index(fields=['datatime'], name='api_deviced_datatim_bbb247_idx')],
                'unique_together': {('deviceuuid', 'name', 'datatime')},
            },
        ),
    ]
