# Generated by Django 5.1.2 on 2024-10-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedata',
            name='name',
            field=models.CharField(choices=[('name1', '設備 1'), ('name2', '設備 2')], max_length=10),
        ),
    ]
