# Generated by Django 4.2.6 on 2024-10-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_devicedata_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceElectricNumberMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("electricnumber", models.CharField(max_length=11)),
                ("deviceuuid", models.CharField(max_length=36)),
                ("registered", models.BooleanField(default=False)),
                ("createtime", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
