# Generated by Django 4.2.6 on 2024-10-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ami", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AMIData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deviceuuid", models.CharField(max_length=36)),
                ("name", models.CharField(blank=True, max_length=10, null=True)),
                ("value", models.FloatField()),
                ("datatime", models.BigIntegerField()),
                ("createtime", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["deviceuuid", "name"],
                        name="ami_amidata_deviceu_69aab6_idx",
                    ),
                    models.Index(
                        fields=["datatime"], name="ami_amidata_datatim_794b89_idx"
                    ),
                ],
                "unique_together": {("deviceuuid", "name", "datatime")},
            },
        ),
    ]
