# Generated by Django 4.2.6 on 2024-10-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ami", "0002_alter_device_createtime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="name",
            field=models.CharField(max_length=10),
        ),
    ]
