# Generated by Django 4.2.6 on 2024-10-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ami", "0003_alter_device_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="registered",
            field=models.BooleanField(default=True),
        ),
    ]
